version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always


  proxy:
    image: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/aiir_course_work.conf
    restart: always
    depends_on:
      - backend

  frontend:
    build:
      context: ./learning_stuff
      dockerfile: Dockerfile
    ports:
      - 10010:80
    restart: always
